### ISSUE TITLE
CoC Range and Is Matching Required?  

### ISSUE THREAD

**Issue by TouqeerAhmad** [feiran-l/Neural-Dual-Pixel-Simulator#1]
Hello, 
I am exploring your simulator for generating Dual-Pixel pairs given the RGBD dataset. 
I was wondering what was the range of your CoC during training?
Also for cross-dataset generalization, do I need to scale the COC so that it matches with the range on which the model is trained. 
Specifically, you are using a lens with 85mm focal length while I am using a dataset shot with 18mm focal length.

Thanks, 
Touqeer

**Comment by feiran-l** [comment]
Hi there,

Yes it would be better to let the CoC in synthesis match the training data. I forgot about the exact range of our training dataset. But in data synthesis, we have empirically [set its numerical value within [-20, 20]](https://github.com/feiran-l/Neural-Dual-Pixel-Simulator/blob/088647ba4f814a1306cea2cd8131e721d02ef57d/our_simulator/process_hypersim/step3_add_config_hypersim.py#L39) by adaptive changing the pixel size.

**Comment by TouqeerAhmad** [comment]
Thank you for clarifying!
