### ISSUE TITLE
Hi，Could you share the dataset  that is accessible in chinese mainland?

### ISSUE THREAD

**Issue by excllent123** [feiran-l/Neural-Dual-Pixel-Simulator#2]
Hi  feiran,
      DropBox  is hard to acess in Chinese mainland,could  you share it on baidu or kaggle?
Thanks

**Comment by feiran-l** [comment]
Hi there,

I haven't used them before. Let me explore it a bit and get back to you

**Comment by feiran-l** [comment]
Hi @excllent123 

Sorry to be late. We have some trouble registering an account for Baidu disk and Kaggle requires the dataset to be no larger than 100GB (our original dataset with 16-bit image is ~143GB). As a temporary workaround, we **converted the 16-bit RGB images to 8-bit** and uploaded them to Kaggle: https://www.kaggle.com/datasets/feiranli/dp5k-dataset/data. Hope this can help you. 

UPDATE: We have uploaded a 16-bit version to OneDrive: https://bupteducn-my.sharepoint.com/personal/guoheng_bupt_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fguoheng%5Fbupt%5Fedu%5Fcn%2FDocuments%2FDataset%2FDP&ga=1
